/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.ventanas;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioFormat;
import static javax.sound.sampled.AudioFormat.Encoding.PCM_SIGNED;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import static javax.sound.sampled.AudioSystem.getAudioInputStream;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.SourceDataLine;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;

/**
 *
 * @author adrianmj
 */
public class LetrasModulo extends javax.swing.JFrame {
    
     private int cont=12;
    
    /**
     * Creates new form LetrasModulo
     */
    public LetrasModulo() throws IOException {
        initComponents();
        setSize(1365, 740);
        ImageIcon imageIconMinus=new ImageIcon("C:\\Users\\usuario\\Desktop\\UPS\\9no CICLO ING SISTEMAS\\INTELIGENCIA ARTIFICIAL\\Modulo1-4\\src\\main\\java\\ec\\edu\\ups\\imagenes\\minus.png");
        ImageIcon imageIconMayus=new ImageIcon("C:\\Users\\usuario\\Desktop\\UPS\\9no CICLO ING SISTEMAS\\INTELIGENCIA ARTIFICIAL\\Modulo1-4\\src\\main\\java\\ec\\edu\\ups\\imagenes\\mayus.png");
        menuItemMinusculas.setIcon(imageIconMinus);
        menuItemMayusculas.setIcon(imageIconMayus);
        
    }
    
   
    
    
     public void play(String filePath) throws UnsupportedAudioFileException {
        final File file = new File(filePath);

        try (final AudioInputStream in = getAudioInputStream(file)) {

            final AudioFormat outFormat = getOutFormat(in.getFormat());
            final DataLine.Info info = new DataLine.Info(SourceDataLine.class, outFormat);

            try (final SourceDataLine line
                    = (SourceDataLine) AudioSystem.getLine(info)) {

                if (line != null) {
                    line.open(outFormat);
                    line.start();
                    stream(getAudioInputStream(outFormat, in), line);
                    line.drain();
                    line.stop();
                }
            }

        } catch (LineUnavailableException | IOException e) {
            throw new IllegalStateException(e);
        }
    }

    private AudioFormat getOutFormat(AudioFormat inFormat) {
        final int ch = inFormat.getChannels();

        final float rate = inFormat.getSampleRate();
        return new AudioFormat(PCM_SIGNED, rate, 16, ch, ch * 2, rate, false);
    }

    private void stream(AudioInputStream in, SourceDataLine line)
            throws IOException {
        final byte[] buffer = new byte[4096];
        for (int n = 0; n != -1; n = in.read(buffer, 0, buffer.length)) {
            line.write(buffer, 0, n);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btna = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnb = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        btnd = new javax.swing.JButton();
        btne = new javax.swing.JButton();
        btnf = new javax.swing.JButton();
        btng = new javax.swing.JButton();
        btnh = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnch = new javax.swing.JButton();
        btni = new javax.swing.JButton();
        btnk = new javax.swing.JButton();
        btnj = new javax.swing.JButton();
        btnl = new javax.swing.JButton();
        btno = new javax.swing.JButton();
        btnq = new javax.swing.JButton();
        btnp = new javax.swing.JButton();
        btnn = new javax.swing.JButton();
        btnm = new javax.swing.JButton();
        btnñ = new javax.swing.JButton();
        btnr = new javax.swing.JButton();
        btns = new javax.swing.JButton();
        btnt = new javax.swing.JButton();
        btnu = new javax.swing.JButton();
        btnv = new javax.swing.JButton();
        btnw = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btny = new javax.swing.JButton();
        btnz = new javax.swing.JButton();
        btnEspacio = new javax.swing.JButton();
        sldLetra = new javax.swing.JSlider();
        lblmenos = new javax.swing.JLabel();
        lblmas = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemMayusculas = new javax.swing.JMenuItem();
        menuItemMinusculas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modulo Alfabeto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1363, 740));

        btna.setBackground(new java.awt.Color(51, 51, 255));
        btna.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btna.setText("a");
        btna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaMouseClicked(evt);
            }
        });
        btna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnb.setBackground(new java.awt.Color(255, 255, 51));
        btnb.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnb.setText("b");
        btnb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbMouseClicked(evt);
            }
        });
        btnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbActionPerformed(evt);
            }
        });

        btnc.setBackground(new java.awt.Color(0, 255, 102));
        btnc.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnc.setText("c");
        btnc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncMouseClicked(evt);
            }
        });
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });

        btnd.setBackground(new java.awt.Color(255, 102, 0));
        btnd.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnd.setText("d");
        btnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndMouseClicked(evt);
            }
        });
        btnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndActionPerformed(evt);
            }
        });

        btne.setBackground(new java.awt.Color(0, 153, 255));
        btne.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btne.setText("e");
        btne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneMouseClicked(evt);
            }
        });
        btne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneActionPerformed(evt);
            }
        });

        btnf.setBackground(new java.awt.Color(204, 255, 204));
        btnf.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnf.setText("f");
        btnf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfMouseClicked(evt);
            }
        });
        btnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfActionPerformed(evt);
            }
        });

        btng.setBackground(new java.awt.Color(102, 153, 255));
        btng.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btng.setText("g");
        btng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngMouseClicked(evt);
            }
        });
        btng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngActionPerformed(evt);
            }
        });

        btnh.setBackground(new java.awt.Color(153, 102, 255));
        btnh.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnh.setText("h");
        btnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhMouseClicked(evt);
            }
        });
        btnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(255, 204, 51));
        btnBorrar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
        });
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        btnBorrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBorrarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnBorrarKeyReleased(evt);
            }
        });

        btnch.setBackground(new java.awt.Color(51, 102, 255));
        btnch.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnch.setText("ch");
        btnch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnchMouseClicked(evt);
            }
        });
        btnch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchActionPerformed(evt);
            }
        });

        btni.setBackground(new java.awt.Color(102, 255, 102));
        btni.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btni.setText("i");
        btni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btniMouseClicked(evt);
            }
        });
        btni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniActionPerformed(evt);
            }
        });

        btnk.setBackground(new java.awt.Color(51, 153, 0));
        btnk.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnk.setText("k");
        btnk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkMouseClicked(evt);
            }
        });
        btnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkActionPerformed(evt);
            }
        });

        btnj.setBackground(new java.awt.Color(255, 153, 0));
        btnj.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnj.setText("j");
        btnj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnjMouseClicked(evt);
            }
        });
        btnj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjActionPerformed(evt);
            }
        });

        btnl.setBackground(new java.awt.Color(102, 255, 102));
        btnl.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnl.setText("l");
        btnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlMouseClicked(evt);
            }
        });
        btnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlActionPerformed(evt);
            }
        });

        btno.setBackground(new java.awt.Color(102, 255, 102));
        btno.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btno.setText("o");
        btno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnoMouseClicked(evt);
            }
        });
        btno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoActionPerformed(evt);
            }
        });

        btnq.setBackground(new java.awt.Color(0, 0, 255));
        btnq.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnq.setText("q");
        btnq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnqMouseClicked(evt);
            }
        });
        btnq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqActionPerformed(evt);
            }
        });

        btnp.setBackground(new java.awt.Color(255, 153, 51));
        btnp.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnp.setText("p");
        btnp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpMouseClicked(evt);
            }
        });
        btnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpActionPerformed(evt);
            }
        });

        btnn.setBackground(new java.awt.Color(0, 255, 153));
        btnn.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnn.setText("n");
        btnn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnMouseClicked(evt);
            }
        });
        btnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnActionPerformed(evt);
            }
        });

        btnm.setBackground(new java.awt.Color(0, 255, 204));
        btnm.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnm.setText("m");
        btnm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmMouseClicked(evt);
            }
        });
        btnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmActionPerformed(evt);
            }
        });

        btnñ.setBackground(new java.awt.Color(255, 51, 51));
        btnñ.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnñ.setText("ñ");
        btnñ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnñMouseClicked(evt);
            }
        });
        btnñ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnñActionPerformed(evt);
            }
        });

        btnr.setBackground(new java.awt.Color(102, 0, 204));
        btnr.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnr.setText("r");
        btnr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrMouseClicked(evt);
            }
        });
        btnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrActionPerformed(evt);
            }
        });

        btns.setBackground(new java.awt.Color(153, 153, 255));
        btns.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btns.setText("s");
        btns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsMouseClicked(evt);
            }
        });
        btns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsActionPerformed(evt);
            }
        });

        btnt.setBackground(new java.awt.Color(255, 255, 51));
        btnt.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnt.setText("t");
        btnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntMouseClicked(evt);
            }
        });
        btnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntActionPerformed(evt);
            }
        });

        btnu.setBackground(new java.awt.Color(255, 204, 204));
        btnu.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnu.setText("u");
        btnu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnuMouseClicked(evt);
            }
        });
        btnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuActionPerformed(evt);
            }
        });

        btnv.setBackground(new java.awt.Color(0, 153, 204));
        btnv.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnv.setText("v");
        btnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvMouseClicked(evt);
            }
        });
        btnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvActionPerformed(evt);
            }
        });

        btnw.setBackground(new java.awt.Color(51, 255, 153));
        btnw.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnw.setText("w");
        btnw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnwMouseClicked(evt);
            }
        });
        btnw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwActionPerformed(evt);
            }
        });

        btnx.setBackground(new java.awt.Color(102, 0, 255));
        btnx.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnx.setText("x");
        btnx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnxMouseClicked(evt);
            }
        });
        btnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxActionPerformed(evt);
            }
        });

        btny.setBackground(new java.awt.Color(102, 255, 153));
        btny.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btny.setText("y");
        btny.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnyMouseClicked(evt);
            }
        });
        btny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyActionPerformed(evt);
            }
        });

        btnz.setBackground(new java.awt.Color(102, 153, 255));
        btnz.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        btnz.setText("z");
        btnz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnzMouseClicked(evt);
            }
        });
        btnz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzActionPerformed(evt);
            }
        });

        btnEspacio.setBackground(new java.awt.Color(153, 255, 153));
        btnEspacio.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnEspacio.setText("Espacio");
        btnEspacio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEspacioMouseClicked(evt);
            }
        });
        btnEspacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspacioActionPerformed(evt);
            }
        });
        btnEspacio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEspacioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnEspacioKeyReleased(evt);
            }
        });

        sldLetra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldLetraStateChanged(evt);
            }
        });

        lblmenos.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblmenos.setText("-");
        lblmenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmenosMousePressed(evt);
            }
        });

        lblmas.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblmas.setText("+");
        lblmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmasMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnq, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btns, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btne, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnf, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btng, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnw, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnx, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btni, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btny, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnz, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnj, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btnk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBorrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnm, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEspacio))
                .addGap(12, 12, 12)
                .addComponent(btnn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(lblmas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnñ, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btng)
                                .addComponent(btnf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btne)
                                .addComponent(btnh)
                                .addComponent(btni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnj)
                                .addComponent(btnk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnñ)
                                .addComponent(btno)
                                .addComponent(btnp))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnr, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btns)
                            .addComponent(btnv, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnw, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnx, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btny, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnz, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmenos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Opciones");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        menuItemMayusculas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuItemMayusculas.setText("Mayúsculas");
        menuItemMayusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMayusculasActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemMayusculas);

        menuItemMinusculas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuItemMinusculas.setText("Minúsculas");
        menuItemMinusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMinusculasActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemMinusculas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaMouseClicked
        try {

            play("C:\\Users\\usuario\\Desktop\\UPS\\9no CICLO ING SISTEMAS\\INTELIGENCIA ARTIFICIAL\\Modulo1-4\\src\\main\\java\\sonidosLetras\\a.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtArea.append(btna.getText());
    }//GEN-LAST:event_btnaMouseClicked

    private void btnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaActionPerformed

    private void btnbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbMouseClicked
        try {
            //txtArea.setText("b");
            play("C:\\Users\\usuario\\Desktop\\UPS\\9no CICLO ING SISTEMAS\\INTELIGENCIA ARTIFICIAL\\Modulo1-4\\src\\main\\java\\sonidosLetras\\b.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnb.getText());
    }//GEN-LAST:event_btnbMouseClicked

    private void btnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbActionPerformed

    private void btncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btncMouseClicked

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\9no CICLO ING SISTEMAS\\INTELIGENCIA ARTIFICIAL\\Modulo1-4\\src\\main\\java\\sonidosLetras\\c.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnc.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_btncActionPerformed

    private void btndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btndMouseClicked

    private void btndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndActionPerformed
        try {
            //txtArea.setText("b");
            play("C:\\Users\\usuario\\Desktop\\UPS\\9no CICLO ING SISTEMAS\\INTELIGENCIA ARTIFICIAL\\Modulo1-4\\src\\main\\java\\sonidosLetras\\d.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnd.getText());
    }//GEN-LAST:event_btndActionPerformed

    private void btneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btneMouseClicked

    private void btneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\e.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btne.getText());
    }//GEN-LAST:event_btneActionPerformed

    private void btnfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfMouseClicked
        
    }//GEN-LAST:event_btnfMouseClicked

    private void btnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\f.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnf.getText());
    }//GEN-LAST:event_btnfActionPerformed

    private void btngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btngMouseClicked

    private void btnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhMouseClicked

    private void btnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\h.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnh.getText());
    }//GEN-LAST:event_btnhActionPerformed

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        String texto = txtArea.getText();
        texto = texto.substring(0, texto.length() - 1);
        txtArea.setText(null);
        txtArea.append(texto);
    }//GEN-LAST:event_btnBorrarMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBorrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBorrarKeyPressed

    }//GEN-LAST:event_btnBorrarKeyPressed

    private void btnBorrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBorrarKeyReleased

    }//GEN-LAST:event_btnBorrarKeyReleased

    private void btnchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnchMouseClicked

    private void btnchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\ch.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnch.getText());
    }//GEN-LAST:event_btnchActionPerformed

    private void btniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btniMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btniMouseClicked

    private void btniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\i.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btni.getText());
    }//GEN-LAST:event_btniActionPerformed

    private void btnkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkMouseClicked

    private void btnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\k.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnk.getText());
    }//GEN-LAST:event_btnkActionPerformed

    private void btnjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnjMouseClicked

    private void btnjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjActionPerformed
       try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\j.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnj.getText());
    }//GEN-LAST:event_btnjActionPerformed

    private void btnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlMouseClicked

    private void btnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\l.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnl.getText());
    }//GEN-LAST:event_btnlActionPerformed

    private void btnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnoMouseClicked

    private void btnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\o.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btno.getText());
    }//GEN-LAST:event_btnoActionPerformed

    private void btnqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnqMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnqMouseClicked

    private void btnqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\q.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnq.getText());
    }//GEN-LAST:event_btnqActionPerformed

    private void btnpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpMouseClicked

    private void btnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\p.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnp.getText());
    }//GEN-LAST:event_btnpActionPerformed

    private void btnnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnMouseClicked

    private void btnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\n.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnn.getText());
    }//GEN-LAST:event_btnnActionPerformed

    private void btnmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmMouseClicked

    private void btnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\m.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnm.getText());
    }//GEN-LAST:event_btnmActionPerformed

    private void btnñMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnñMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnñMouseClicked

    private void btnñActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnñActionPerformed
            try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\ñ.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnñ.getText());
    }//GEN-LAST:event_btnñActionPerformed

    private void btnrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrMouseClicked

    private void btnrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\r.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnr.getText());
    }//GEN-LAST:event_btnrActionPerformed

    private void btnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsMouseClicked

    private void btnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\s.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btns.getText());
    }//GEN-LAST:event_btnsActionPerformed

    private void btntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btntMouseClicked

    private void btntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntActionPerformed
       try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\t.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnt.getText());
    }//GEN-LAST:event_btntActionPerformed

    private void btnuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnuMouseClicked

    private void btnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuActionPerformed
       try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\u.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnu.getText());
    }//GEN-LAST:event_btnuActionPerformed

    private void btnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvMouseClicked

    private void btnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\v.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnv.getText());
    }//GEN-LAST:event_btnvActionPerformed

    private void btnwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnwMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnwMouseClicked

    private void btnwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\w.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnw.getText());
    }//GEN-LAST:event_btnwActionPerformed

    private void btnxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxMouseClicked

    private void btnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxActionPerformed
       try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\x.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnx.getText());
    }//GEN-LAST:event_btnxActionPerformed

    private void btnyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnyMouseClicked

    private void btnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\y.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btny.getText());
    }//GEN-LAST:event_btnyActionPerformed

    private void btnzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnzMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnzMouseClicked

    private void btnzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzActionPerformed
       try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\z.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btnz.getText());
    }//GEN-LAST:event_btnzActionPerformed

    private void btnEspacioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspacioMouseClicked
        txtArea.append(" ");
    }//GEN-LAST:event_btnEspacioMouseClicked

    private void btnEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEspacioActionPerformed

    private void btnEspacioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEspacioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEspacioKeyPressed

    private void btnEspacioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEspacioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEspacioKeyReleased

    private void sldLetraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldLetraStateChanged
        int tamano =new Integer(sldLetra.getValue());             
        //txtArea.setBackground(Color.red);
        Font fuente = new Font("Dialog", Font.BOLD, tamano);
        txtArea.setFont(fuente);
    }//GEN-LAST:event_sldLetraStateChanged

    private void menuItemMayusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMayusculasActionPerformed
        btna.setText("A");
        btnb.setText("B");
        btnc.setText("C");
        btnch.setText("CH");
        btnd.setText("D");
        btne.setText("E");
        btnf.setText("F");
        btng.setText("G");
        btnh.setText("H");
        btni.setText("I");
        btnj.setText("J");
        btnk.setText("K");
        btnl.setText("L");
        btnm.setText("M");
        btnn.setText("N");
        btnñ.setText("Ñ");
        btno.setText("O");
        btnp.setText("P");
        btnq.setText("Q");
        btnr.setText("R");
        btns.setText("S");
        btnt.setText("T");
        btnu.setText("U");
        btnv.setText("V");
        btnw.setText("W");
        btnx.setText("X");
        btny.setText("Y");
        btnz.setText("Z");
        btnBorrar.setText("BORRAR");
        btnEspacio.setText("ESPACIO");
    }//GEN-LAST:event_menuItemMayusculasActionPerformed

    private void lblmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmasMouseClicked
       
       
       
       
        
      
    }//GEN-LAST:event_lblmasMouseClicked

    private void lblmasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmasMousePressed
        Font fuente = new Font("Dialog", Font.BOLD, cont);    
        txtArea.setFont(fuente);
        System.out.println("");
        cont+=14;
    }//GEN-LAST:event_lblmasMousePressed

    private void lblmenosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmenosMousePressed
        Font fuente = new Font("Dialog", Font.BOLD, cont);    
        txtArea.setFont(fuente);
        cont-=14;
    }//GEN-LAST:event_lblmenosMousePressed

    private void menuItemMinusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMinusculasActionPerformed
        btna.setText("a");
        btnb.setText("b");
        btnc.setText("c");
        btnch.setText("ch");
        btnd.setText("d");
        btne.setText("e");
        btnf.setText("f");
        btng.setText("g");
        btnh.setText("h");
        btni.setText("i");
        btnj.setText("j");
        btnk.setText("k");
        btnl.setText("l");
        btnm.setText("m");
        btnn.setText("n");
        btnñ.setText("ñ");
        btno.setText("o");
        btnp.setText("p");
        btnq.setText("q");
        btnr.setText("r");
        btns.setText("s");
        btnt.setText("t");
        btnu.setText("u");
        btnv.setText("v");
        btnw.setText("w");
        btnx.setText("x");
        btny.setText("y");
        btnz.setText("z");
        btnBorrar.setText("borrar");
        btnEspacio.setText("espacio");
    }//GEN-LAST:event_menuItemMinusculasActionPerformed

    private void btngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngActionPerformed
        try {
            play("C:\\Users\\usuario\\Desktop\\UPS\\Pasantias San Jose de Calasanz\\PasatiasSJ\\src\\sonidosLetras\\g.mp3");
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtArea.append(btng.getText());
    }//GEN-LAST:event_btngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LetrasModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LetrasModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LetrasModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LetrasModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LetrasModulo().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(LetrasModulo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEspacio;
    private javax.swing.JButton btna;
    private javax.swing.JButton btnb;
    private javax.swing.JButton btnc;
    private javax.swing.JButton btnch;
    private javax.swing.JButton btnd;
    private javax.swing.JButton btne;
    private javax.swing.JButton btnf;
    private javax.swing.JButton btng;
    private javax.swing.JButton btnh;
    private javax.swing.JButton btni;
    private javax.swing.JButton btnj;
    private javax.swing.JButton btnk;
    private javax.swing.JButton btnl;
    private javax.swing.JButton btnm;
    private javax.swing.JButton btnn;
    private javax.swing.JButton btno;
    private javax.swing.JButton btnp;
    private javax.swing.JButton btnq;
    private javax.swing.JButton btnr;
    private javax.swing.JButton btns;
    private javax.swing.JButton btnt;
    private javax.swing.JButton btnu;
    private javax.swing.JButton btnv;
    private javax.swing.JButton btnw;
    private javax.swing.JButton btnx;
    private javax.swing.JButton btny;
    private javax.swing.JButton btnz;
    private javax.swing.JButton btnñ;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblmas;
    private javax.swing.JLabel lblmenos;
    private javax.swing.JMenuItem menuItemMayusculas;
    private javax.swing.JMenuItem menuItemMinusculas;
    private javax.swing.JSlider sldLetra;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
