/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.ventanas;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author adrianmj
 */
public class ModuloProfesor extends javax.swing.JFrame {

    /**
     * Creates new form ModuloProfesor
     */
    public ModuloProfesor() {
        initComponents();
       // setSize(900, 700);
    }

    public void listarFicherosPorCarpeta(final File carpeta) {
        for (final File ficheroEntrada : carpeta.listFiles()) {
            if (ficheroEntrada.isDirectory()) {
                listarFicherosPorCarpeta(ficheroEntrada);
            } else {
                String ficheros = ficheroEntrada.getName();
                String[] sep = ficheros.split(".txt");
                for (int i = 0; i < sep.length; i++) {
                    JOptionPane.showMessageDialog(rootPane, sep[i].toString());

                }

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        menuItemActividad = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cargarActividad = new javax.swing.JMenuItem();
        menuItemDelete = new javax.swing.JMenuItem();
        teachWord = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modulo de Profesor");
        setExtendedState(MAXIMIZED_BOTH);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Iniciar");

        cargarActividad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        cargarActividad.setText("Cargar Palabra(s) de Enseñanza");
        cargarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActividadActionPerformed(evt);
            }
        });
        jMenu1.add(cargarActividad);

        menuItemDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuItemDelete.setText("Eliminar Palabras(s) de Enseñanza");
        menuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDeleteActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemDelete);

        teachWord.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        teachWord.setText("Enseñar Palabra");
        teachWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachWordActionPerformed(evt);
            }
        });
        jMenu1.add(teachWord);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Actividad Alumno");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Pizarra del Profesor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuItemActividad.add(jMenu1);
        menuItemActividad.add(jMenu2);

        setJMenuBar(menuItemActividad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActividadActionPerformed
        CargarPalabraEnseñar ap = new CargarPalabraEnseñar();
        escritorio.add(ap);
        ap.setVisible(true);
    }//GEN-LAST:event_cargarActividadActionPerformed

    private void teachWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachWordActionPerformed
        PalabraEnseñar enseñar = new PalabraEnseñar();
        escritorio.add(enseñar);
        enseñar.setVisible(true);
    }//GEN-LAST:event_teachWordActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        /*  TareaAlumno ta = new TareaAlumno();
         escritorio.add(ta);
         ta.setVisible(true);
         */
        ActividadAlumno ao = new ActividadAlumno();
        escritorio.add(ao);
        ao.setVisible(true);


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDeleteActionPerformed
        try {
            JFileChooser file = new JFileChooser("C:\\Users\\usuario\\Desktop\\UPS\\9no CICLO ING SISTEMAS\\INTELIGENCIA ARTIFICIAL\\Modulo1-4\\src\\main\\java\\ec\\edu\\ups\\actividades\\");
            file.showOpenDialog(this);
            File archivo = file.getSelectedFile();
            if (archivo != null) {
                archivo.delete();
                JOptionPane.showMessageDialog(rootPane, "El archivo ha sido eliminado con éxito!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Eliminando Archivo - " + e.getMessage());
        }
    }//GEN-LAST:event_menuItemDeleteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PizarraProfesor pp = new PizarraProfesor();
        escritorio.add(pp);
        pp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cargarActividad;
    public static javax.swing.JPanel escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuItemActividad;
    private javax.swing.JMenuItem menuItemDelete;
    private javax.swing.JMenuItem teachWord;
    // End of variables declaration//GEN-END:variables
}
