/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.ventanas;

import static ec.edu.ups.ventanas.ModuloProfesor.escritorio;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author adrianmj
 */
public class PalabraEnseñar extends javax.swing.JInternalFrame {

    /**
     * Creates new form EnseñarPalabra
     */
    public PalabraEnseñar() {
        initComponents();
        final File carpeta = new File("C:\\Users\\usuario\\Desktop\\UPS\\9no CICLO ING SISTEMAS\\INTELIGENCIA ARTIFICIAL\\Modulo1-4\\src\\main\\java\\ec\\edu\\ups\\actividades\\");
        listarFicherosPorCarpeta(carpeta);
    }

    public String enviarDato() {
        String dato = txtPalabraAbuscar.getText().toString();
        return dato;
    }

    public void listarFicherosPorCarpeta(final File carpeta) {
        for (final File ficheroEntrada : carpeta.listFiles()) {
            if (ficheroEntrada.isDirectory()) {
                listarFicherosPorCarpeta(ficheroEntrada);
            } else {
                String ficheros = ficheroEntrada.getName();
                String[] sep = ficheros.split(".txt");
                for (int i = 0; i < sep.length; i++) {
                    txtListaPalabras.append("\n" + sep[i]);
                }

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTeach = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtPalabraAbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtListaPalabras = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Palabra a enseñar");

        btnTeach.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTeach.setText("Enseñar");
        btnTeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeachActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        txtPalabraAbuscar.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel1.setText("Palabra:");

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel2.setText("Lista de palabras:");

        txtListaPalabras.setColumns(20);
        txtListaPalabras.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        txtListaPalabras.setForeground(new java.awt.Color(0, 0, 204));
        txtListaPalabras.setRows(5);
        jScrollPane2.setViewportView(txtListaPalabras);

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTeach)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addGap(205, 205, 205)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(txtPalabraAbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPalabraAbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeach)
                    .addComponent(btnLimpiar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeachActionPerformed

        try {
            if (!txtPalabraAbuscar.getText().isEmpty()) {
                String texto = " ";
                FileReader lector = new FileReader("C:\\Users\\usuario\\Desktop\\UPS\\9no CICLO ING SISTEMAS\\INTELIGENCIA ARTIFICIAL\\Modulo1-4\\src\\main\\java\\ec\\edu\\ups\\actividades\\" + txtPalabraAbuscar.getText() + ".txt");
                BufferedReader contenido = new BufferedReader(lector);
                while ((texto = contenido.readLine()) != null) {
                    String[] textoSeparar = texto.split(";");
                    for (int i = 0; i < textoSeparar.length; i++) {
                        txtArea.append("\n" + textoSeparar[i]);
                        
                        //enviarDato();
                    }
                    
                }
                         
            } else if (txtPalabraAbuscar.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, " Por favor ingrese una palabra");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PalabraEnseñar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PalabraEnseñar.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnTeachActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtArea.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnTeach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextArea txtListaPalabras;
    public static javax.swing.JTextField txtPalabraAbuscar;
    // End of variables declaration//GEN-END:variables
}
